-- Create table for product sizes configuration
CREATE TABLE IF NOT EXISTS `product_sizes_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_id` int(11) NOT NULL,
  `size_type` varchar(50) NOT NULL,
  `size_value` varchar(20) NOT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_product_size` (`product_id`, `size_type`, `size_value`),
  KEY `idx_product_id` (`product_id`),
  KEY `idx_size_type` (`size_type`),
  FOREIGN KEY (`product_id`) REFERENCES `production_ready_products`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Add support for products without sizes
ALTER TABLE `product_sizes_config` ADD COLUMN IF NOT EXISTS `no_sizes` tinyint(1) DEFAULT 0;

-- Insert default size types and values
INSERT IGNORE INTO `product_sizes_config` (`product_id`, `size_type`, `size_value`, `is_active`) VALUES
-- Example for product ID 1 (you can modify as needed)
(1, 'clothing', 'xs', 0),
(1, 'clothing', 's', 0),
(1, 'clothing', 'm', 0),
(1, 'clothing', 'l', 0),
(1, 'clothing', 'xl', 0),
(1, 'clothing', 'xxl', 0),
(1, 'clothing', '3xl', 0),
(1, 'clothing', '4xl', 0),
(1, 'numeric_pants', '30', 0),
(1, 'numeric_pants', '31', 0),
(1, 'numeric_pants', '32', 0),
(1, 'numeric_pants', '33', 0),
(1, 'numeric_pants', '34', 0),
(1, 'numeric_pants', '36', 0),
(1, 'numeric_pants', '38', 0),
(1, 'numeric_pants', '40', 0),
(1, 'numeric_pants', '42', 0),
(1, 'numeric_pants', '44', 0),
(1, 'numeric_pants', '46', 0),
(1, 'numeric_pants', '48', 0),
(1, 'numeric_pants', '50', 0),
(1, 'numeric_pants', '52', 0),
(1, 'numeric_pants', '54', 0),
(1, 'numeric_pants', '56', 0),
(1, 'numeric_pants', '58', 0),
(1, 'numeric_pants', '60', 0),
(1, 'numeric_pants', '62', 0),
(1, 'numeric_pants', '64', 0),
(1, 'numeric_pants', '66', 0),
(1, 'shoes', '39', 0),
(1, 'shoes', '40', 0),
(1, 'shoes', '41', 0),
(1, 'shoes', '42', 0),
(1, 'shoes', '43', 0),
(1, 'shoes', '44', 0),
(1, 'shoes', '45', 0),
(1, 'shoes', '46', 0),
(1, 'shoes', '47', 0),
(1, 'belts', '85', 0),
(1, 'belts', '90', 0),
(1, 'belts', '95', 0),
(1, 'belts', '100', 0),
(1, 'belts', '105', 0),
(1, 'belts', '110', 0),
(1, 'belts', '115', 0),
(1, 'belts', '120', 0),
(1, 'belts', '125', 0);